# Site settings
title: Matthew M. Osborn
header-img: img/headers/default.jpg
description: "The website and blog of Matthew M. Osborn"
baseurl: ""
url: "http://osbornm.com"
twitter_username: osbonrm
github_username:  osbornm
instagram_username: osbornmatthew
500px_username: osbornm
stackoverflow_username: 5235/matthew-m-osborn

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


